[tool.poetry]
name = "ioc-checker"
version = "0.1.0"
description = ""
authors = ["Ibrahim <ibrahim-ehab@live.com>"]
readme = "README.md"
packages = [{ include = "IOC_Checker_Python" }]

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.27"
httpx-cache = "^0.13"
aiolimiter = "^1.0"
pydantic = "^2.7"
filelock = "^3.14"
requests-cache = "^1.2"
pytest = { version = "^8.0", optional = true }

[tool.poetry.extras]
test = ["pytest"]

[tool.poetry.scripts]
ioc-checker = "IOC_Checker_Python.ioc_checker:main"
ioc-checker-gui = "IOC_Checker_Python.ioc_gui_tk:run_gui"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120

[tool.mypy]
strict = true
